# fly.toml app configuration file generated for still-silence-1519 on 2023-07-19T04:54:41Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "still-silence-1519"
primary_region = "ord"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
